---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/certificate_authority/.aar_doc.yml
      - roles/certificate_authority/README.md
      - roles/certificate_authority/meta/argument_specs.yml
      - roles/certificate_authority/meta/main.yml
      - roles/signed_certificate/.aar_doc.yml
      - roles/signed_certificate/README.md
      - roles/signed_certificate/meta/argument_specs.yml
      - roles/signed_certificate/meta/main.yml
      - roles/sub_ca_certificate/.aar_doc.yml
      - roles/sub_ca_certificate/README.md
      - roles/sub_ca_certificate/meta/argument_specs.yml
      - roles/sub_ca_certificate/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.adcs'
jobs:
  docs_certificate_authority:
    name: Generate certificate_authority role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.adcs
          ref: main
      - name: Generate certificate_authority role documentation
        working-directory: 'trippsc2.adcs'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/certificate_authority
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update certificate_authority role documentation." || /bin/true
          git push origin main
          deactivate
  docs_signed_certificate:
    name: Generate signed_certificate role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.adcs
          ref: main
      - name: Generate signed_certificate role documentation
        working-directory: 'trippsc2.adcs'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/signed_certificate
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update signed_certificate role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_certificate_authority
  docs_sub_ca_certificate:
    name: Generate sub_ca_certificate role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.adcs
          ref: main
      - name: Generate sub_ca_certificate role documentation
        working-directory: 'trippsc2.adcs'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/sub_ca_certificate
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update sub_ca_certificate role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_signed_certificate
