---
name: Molecule - certificate_authority role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/certificate_authority/**
      - '!roles/certificate_authority/.aar_doc.yml'
      - '!roles/certificate_authority/README.md'
      - '!roles/certificate_authority/meta/argument_specs.yml'
      - '!roles/certificate_authority/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/certificate_authority/**
      - '!roles/certificate_authority/.aar_doc.yml'
      - '!roles/certificate_authority/README.md'
      - '!roles/certificate_authority/meta/argument_specs.yml'
      - '!roles/certificate_authority/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.adcs'
jobs:
  molecule:
    name: Run Molecule tests - certificate_authority
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.adcs
      - name: Run Molecule tests
        working-directory: 'trippsc2.adcs'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/certificate_authority
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
